# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [216]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [217]:
#Step 1L Load data
AviationData = pd.read_csv("AviationData.csv")
AviationData.head()

/tmp/ipykernel_2725/161692237.py:2: DtypeWarning: Columns (6: Latitude, 7: Longitude, 28: Broad.phase.of.flight) have mixed types. Specify dtype option on import or set low_memory=False.
  AviationData = pd.read_csv("AviationData.csv")

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [218]:
#make a working copy of the data
AviationData_Copy = AviationData.copy()
AviationData_Copy.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [219]:
#Check for data types
print(AviationData_Copy.dtypes)

Event.Id                      str
Investigation.Type            str
Accident.Number               str
Event.Date                    str
Location                      str
Country                       str
Latitude                   object
Longitude                  object
Airport.Code                  str
Airport.Name                  str
Injury.Severity               str
Aircraft.damage               str
Aircraft.Category             str
Registration.Number           str
Make                          str
Model                         str
Amateur.Built                 str
Number.of.Engines         float64
Engine.Type                   str
FAR.Description               str
Schedule                      str
Purpose.of.flight             str
Air.carrier                   str
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition             str
Broad.phase.of.flight         str
Report.Status                 str
Publication.Date              str
dtype: object

In [220]:
#step 4: Inspect for null/ missing and duplicate values
print(AviationData_Copy.isnull().sum())

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [221]:
#statistical summary
AviationData_Copy.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [222]:
print(AviationData_Copy.columns.tolist())

['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']

In [223]:
AviationData_Copy["Aircraft.Category"].unique()

<StringArray>
[                nan,          'Airplane',        'Helicopter',
            'Glider',           'Balloon',         'Gyrocraft',
        'Ultralight',           'Unknown',             'Blimp',
      'Powered-Lift',      'Weight-Shift', 'Powered Parachute',
            'Rocket',              'WSFT',               'UNK',
              'ULTR']
Length: 16, dtype: str

In [224]:
#Since the client is only interested in airplanes
AviationData_Copy = AviationData_Copy[AviationData_Copy["Aircraft.Category"] == "Airplane"]
AviationData_Copy["Aircraft.Category"].unique()

<StringArray>
['Airplane']
Length: 1, dtype: str

In [225]:
#Client is only interested in professional builds
AviationData_Copy["Amateur.Built"].unique()

<StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

In [226]:
#Excluded all amateur built planes and whose built was unknown
AviationData_Copy = AviationData_Copy[AviationData_Copy["Amateur.Built"] == "No"]
AviationData_Copy["Amateur.Built"].describe()

count     24417
unique        1
top          No
freq      24417
Name: Amateur.Built, dtype: object

In [227]:
#filtering date from 1983 onwards
AviationData_Copy["Event.Date"] = pd.to_datetime(AviationData_Copy["Event.Date"], errors="coerce")

# Keep events from 1983 onwards
AviationData_Copy = AviationData_Copy[AviationData_Copy["Event.Date"].dt.year >= 1983]
AviationData_Copy.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,Unknown,NaN,NaN,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,"Singapore Airlines, Ltd.",NaN,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,Skydiving,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016

In [228]:
print(AviationData_Copy["Event.Date"].min())
print(AviationData_Copy["Event.Date"].max())

1983-03-18 00:00:00
2022-12-26 00:00:00

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

In [229]:
#the total number of injuries
AviationData_Copy["Total.Injuries"] = (
    AviationData_Copy["Total.Fatal.Injuries"]
    + AviationData_Copy["Total.Serious.Injuries"]
    + AviationData_Copy["Total.Minor.Injuries"]
    + AviationData_Copy["Total.Uninjured"]
)
AviationData_Copy

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Injuries
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014,NaN
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,"Singapore Airlines, Ltd.",NaN,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014,NaN
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011,NaN
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016,NaN
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,1.0
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,1.0
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,1.0
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,1.0
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,1.0

In [230]:
#estimating the total number of passengers
AviationData_Copy["Total.Passengers"] = (
    AviationData_Copy["Total.Fatal.Injuries"]
    + AviationData_Copy["Total.Serious.Injuries"]
    + AviationData_Copy["Total.Minor.Injuries"]
    + AviationData_Copy["Total.Uninjured"]
)

In [231]:
#since the client requires reliable aircraft safety comparisons, I consider excluding records with incomplete injury information from the total injury-rate calculation
AviationData_Copy = AviationData_Copy.dropna(subset="Total.Injuries")
AviationData_Copy.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Injuries,Total.Passengers
25965,20001212X23574,Accident,ANC90LA112,1990-07-05,"COLDFOOT, AK",United States,NaN,NaN,NONE,COLDFOOT STRIP,...,1.0,1.0,0.0,0.0,VMC,Descent,Probable Cause,19-03-2009,2.0,2.0
28791,20001212X17738,Accident,ANC91LA117,1991-08-07,"SEWARD, AK",United States,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,VMC,Maneuvering,Probable Cause,19-03-2009,2.0,2.0
28804,20001212X17742,Accident,ANC91LA121,1991-08-09,"ANCHORAGE, AK",United States,NaN,NaN,LHD,LAKE HOOD SEAPLANE,...,0.0,0.0,0.0,1.0,VMC,Takeoff,Probable Cause,19-03-2009,1.0,1.0
30062,20001211X14270,Accident,DCA92MA025,1992-03-22,"FLUSHING, NY",United States,NaN,NaN,LGA,LAGUARDIA,...,27.0,9.0,12.0,3.0,IMC,Takeoff,Probable Cause,14-02-2018,51.0,51.0
34275,20001211X13814,Accident,ANC94LA026,1993-12-12,"PORT LIONS, AK",United States,NaN,NaN,ORI,PORT LIONS,...,0.0,0.0,0.0,5.0,VMC,Landing,Probable Cause,19-03-2009,5.0,5.0

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [232]:
AviationData_Copy["Fatal_Serious_Injury_Rate"] = (
    AviationData_Copy["Total.Fatal.Injuries"] + AviationData_Copy["Total.Serious.Injuries"]
) / AviationData_Copy["Total.Passengers"]

In [233]:
#Aircraft damage
print(AviationData_Copy.columns.tolist())

['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'Total.Injuries', 'Total.Passengers', 'Fatal_Serious_Injury_Rate']

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [234]:
AviationData_Copy = AviationData_Copy.dropna(subset="Aircraft.damage")

In [235]:
AviationData_Copy["Aircraft_destroyed"] = AviationData_Copy["Aircraft.damage"].apply(
    lambda x: "Yes" if x == "Destroyed" else "No"
)

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [236]:
AviationData_Copy["Make"].unique()

<StringArray>
[                'Piper',              'Bellanca',                'Fokker',
               'Douglas',     'Mcdonnell Douglas',                'Boeing',
                'Mooney',                'Cessna',            'Bombardier',
      'Airbus Industrie',
 ...
         'SCOTT TERRY G',              'BEARHAWK', 'ECLIPSE AEROSPACE INC',
       'PIPISTREL D O O',   'MULHOLLAND ROBERT A',                  'BELL',
      'DETRICK DONALD G',               'PHANTOM',     'JAMES R DERNOVSEK',
         'ORLICAN S R O']
Length: 1217, dtype: str

In [237]:
AviationData_Copy["Make"] = (
    AviationData_Copy["Make"].str.strip().str.lower()
)

In [238]:
# Count the number of records for each make
make_counts = AviationData_Copy["Make"].value_counts()

# Identify makes with at least 50 records
common_makes = make_counts[make_counts >= 50].index


# Keep only those makes
AviationData_Copy = AviationData_Copy[AviationData_Copy["Make"].isin(common_makes)].copy()
AviationData_Copy["Make"].describe()

count      14019
unique        30
top       cessna
freq        5803
Name: Make, dtype: object

In [239]:
# Display the remaining makes and their record counts
print(AviationData_Copy["Make"].value_counts())

# Confirm the minimum count is at least 50
print(AviationData_Copy["Make"].value_counts().min())

Make
cessna                            5803
piper                             3392
beech                             1231
boeing                             591
mooney                             300
air tractor inc                    218
cirrus design corp                 216
bellanca                           176
maule                              171
aeronca                            168
air tractor                        163
champion                           131
cirrus                             126
luscombe                           113
stinson                            112
grumman                            107
north american                      98
dehavilland                         91
airbus                              88
embraer                             82
aero commander                      76
aviat aircraft inc                  75
diamond aircraft ind inc            74
taylorcraft                         73
socata                              68
raytheon aircraft company           60
grumman acft eng cor-schweizer      58
rockwell international              55
de havilland                        53
american champion aircraft          50
Name: count, dtype: int64
50

In [240]:
AviationData_Copy.columns.tolist()

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date',
 'Total.Injuries',
 'Total.Passengers',
 'Fatal_Serious_Injury_Rate',
 'Aircraft_destroyed']

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [241]:
#inspecting model columns
AviationData_Copy["Model"].describe()

count     14010
unique     1546
top         172
freq        704
Name: Model, dtype: object

In [242]:
AviationData_Copy["Model"].unique()

<StringArray>
['PA-28-180',     '7GCBC',     'PA-18',     'PA-32',       '767',      'M20E',
 'PA-28-181',      '182H',   '747-200',      'M20R',
 ...
       '700',      'C172',  'BC12D-85',  'MX-7-160',     '787-9',     'DA 62',
    'J3F-60',     'T206G',  'M-7-235B',     'PA-44']
Length: 1547, dtype: str

In [243]:
AviationData_Copy["Model"].isna().sum()

np.int64(9)

In [244]:
AviationData_Copy = AviationData_Copy.dropna(subset = ["Model"])

In [245]:
# View the Make and Model columns
AviationData_Copy[["Make", "Model"]].head(10)

           Make      Model
25965     piper  PA-28-180
28791  bellanca      7GCBC
28804     piper      PA-18
34275     piper      PA-32
40930    boeing        767
50420    mooney       M20E
50682     piper  PA-28-181
54904    cessna       182H
59362    boeing    747-200
61787    mooney       M20R

In [246]:
AviationData_Copy["Make"].value_counts()

Make
cessna                            5800
piper                             3391
beech                             1231
boeing                             588
mooney                             300
air tractor inc                    218
cirrus design corp                 216
bellanca                           176
maule                              171
aeronca                            168
air tractor                        163
champion                           131
cirrus                             126
luscombe                           113
stinson                            112
grumman                            107
north american                      98
dehavilland                         91
airbus                              88
embraer                             81
aero commander                      76
aviat aircraft inc                  75
diamond aircraft ind inc            74
taylorcraft                         73
socata                              68
raytheon aircraft company           60
grumman acft eng cor-schweizer      58
rockwell international              55
de havilland                        52
american champion aircraft          50
Name: count, dtype: int64

In [247]:
AviationData_Copy["Model"].value_counts()

Model
172         704
182         273
PA28        268
152         231
SR22        230
           ...
DA 62         1
J3F-60        1
T206G         1
M-7-235B      1
PA-44         1
Name: count, Length: 1546, dtype: int64

In [248]:
AviationData_Copy.groupby(["Make", "Model"]).size().sort_values(ascending=False)

Make            Model
cessna          172        704
                182        273
piper           PA28       268
cessna          152        231
                172S       194
                          ...
aero commander  680FL        1
                680E         1
                200          1
                500 - B      1
cessna          320F         1
Length: 1627, dtype: int64

In [249]:
print(AviationData_Copy["Make"].value_counts(dropna=False))
print(AviationData_Copy["Model"].value_counts(dropna=False))

Make
cessna                            5800
piper                             3391
beech                             1231
boeing                             588
mooney                             300
air tractor inc                    218
cirrus design corp                 216
bellanca                           176
maule                              171
aeronca                            168
air tractor                        163
champion                           131
cirrus                             126
luscombe                           113
stinson                            112
grumman                            107
north american                      98
dehavilland                         91
airbus                              88
embraer                             81
aero commander                      76
aviat aircraft inc                  75
diamond aircraft ind inc            74
taylorcraft                         73
socata                              68
raytheon aircraft company           60
grumman acft eng cor-schweizer      58
rockwell international              55
de havilland                        52
american champion aircraft          50
Name: count, dtype: int64
Model
172         704
182         273
PA28        268
152         231
SR22        230
           ...
DA 62         1
J3F-60        1
T206G         1
M-7-235B      1
PA-44         1
Name: count, Length: 1546, dtype: int64

In [250]:
model_make_counts = (
    AviationData_Copy.groupby("Model")["Make"].nunique()
)

model_make_counts[model_make_counts > 1]

Model
100      2
112      2
112A     2
1900D    2
200      2
        ..
SF50     2
SR-22    2
SR20     2
SR22     2
SR22T    2
Name: Make, Length: 73, dtype: int64

In [251]:
AviationData_Copy["Make_Model"] = (
    AviationData_Copy["Make"] + " " + AviationData_Copy["Model"]
)
AviationData_Copy.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Injuries,Total.Passengers,Fatal_Serious_Injury_Rate,Aircraft_destroyed,Make_Model
25965,20001212X23574,Accident,ANC90LA112,1990-07-05,"COLDFOOT, AK",United States,NaN,NaN,NONE,COLDFOOT STRIP,...,0.0,VMC,Descent,Probable Cause,19-03-2009,2.0,2.0,1.000000,Yes,piper PA-28-180
28791,20001212X17738,Accident,ANC91LA117,1991-08-07,"SEWARD, AK",United States,NaN,NaN,NaN,NaN,...,1.0,VMC,Maneuvering,Probable Cause,19-03-2009,2.0,2.0,0.000000,No,bellanca 7GCBC
28804,20001212X17742,Accident,ANC91LA121,1991-08-09,"ANCHORAGE, AK",United States,NaN,NaN,LHD,LAKE HOOD SEAPLANE,...,1.0,VMC,Takeoff,Probable Cause,19-03-2009,1.0,1.0,0.000000,No,piper PA-18
34275,20001211X13814,Accident,ANC94LA026,1993-12-12,"PORT LIONS, AK",United States,NaN,NaN,ORI,PORT LIONS,...,5.0,VMC,Landing,Probable Cause,19-03-2009,5.0,5.0,0.000000,No,piper PA-32
40930,20001208X07017,Accident,DCA97WA011,1996-11-23,"COMORSO ISLANDS, Ethiopia",Ethiopia,NaN,NaN,NaN,NaN,...,4.0,VMC,NaN,Foreign,NaN,175.0,175.0,0.965714,Yes,boeing 767

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [252]:
AviationData_Copy.columns.tolist()

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date',
 'Total.Injuries',
 'Total.Passengers',
 'Fatal_Serious_Injury_Rate',
 'Aircraft_destroyed',
 'Make_Model']

In [253]:
#engine type
AviationData_Copy["Engine.Type"].unique()

<StringArray>
[  'Reciprocating',         'Unknown',       'Turbo Fan',       'Turbo Jet',
               nan,      'Turbo Prop',     'Turbo Shaft', 'Geared Turbofan',
             'UNK']
Length: 9, dtype: str

In [254]:
AviationData_Copy["Engine.Type"].isna().sum()

np.int64(2437)

In [255]:
columns_to_check = [
    "Engine.Type",
    "Weather.Condition",
    "Number.of.Engines",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(AviationData_Copy[col].value_counts(dropna=False))

--- Engine.Type ---
Engine.Type
Reciprocating      10492
NaN                 2437
Turbo Prop           739
Turbo Fan            295
Turbo Jet             30
Unknown               10
Turbo Shaft            5
Geared Turbofan        1
UNK                    1
Name: count, dtype: int64

--- Weather.Condition ---
Weather.Condition
VMC    11495
NaN     1654
IMC      722
Unk      139
Name: count, dtype: int64

--- Number.of.Engines ---
Number.of.Engines
1.0    10915
2.0     1695
NaN     1355
4.0       40
3.0        5
Name: count, dtype: int64

--- Purpose.of.flight ---
Purpose.of.flight
Personal                     8220
Instructional                1930
NaN                          1847
Aerial Application            585
Business                      337
Positioning                   208
Unknown                       163
Aerial Observation            133
Skydiving                     103
Other Work Use                100
Banner Tow                     73
Flight Test                    67
Ferry                          61
Executive/corporate            54
Glider Tow                     28
Public Aircraft - Federal      26
Public Aircraft - State        18
Public Aircraft                16
Air Race show                  12
Firefighting                   11
Public Aircraft - Local        11
PUBS                            3
Air Drop                        2
ASHO                            2
Name: count, dtype: int64

--- Broad.phase.of.flight ---
Broad.phase.of.flight
NaN            13951
Cruise            15
Approach          11
Takeoff            9
Maneuvering        6
Landing            6
Descent            4
Climb              4
Unknown            3
Go-around          1
Name: count, dtype: int64

In [256]:
AviationData_Copy["Engine.Type"] = (
    AviationData_Copy["Engine.Type"]
    .str.strip()
    .str.upper()
)

In [257]:
AviationData_Copy["Weather.Condition"].value_counts(dropna=False)

Weather.Condition
VMC    11495
NaN     1654
IMC      722
Unk      139
Name: count, dtype: int64

In [258]:
AviationData_Copy["Weather.Condition"] = (
    AviationData_Copy["Weather.Condition"]
    .str.strip()
    .str.upper()
    .replace(["UNK", "UNKNOWN", ""], np.nan)
)

In [259]:
print(AviationData_Copy["Number.of.Engines"].value_counts(dropna=False))
print(AviationData_Copy["Number.of.Engines"].dtype)

Number.of.Engines
1.0    10915
2.0     1695
NaN     1355
4.0       40
3.0        5
Name: count, dtype: int64
float64

In [260]:
AviationData_Copy["Number.of.Engines"] = pd.to_numeric(
    AviationData_Copy["Number.of.Engines"],
    errors="coerce"
)

print(
    AviationData_Copy.loc[
        AviationData_Copy["Number.of.Engines"].notna()
        & (
            (AviationData_Copy["Number.of.Engines"] < 1)
            | (AviationData_Copy["Number.of.Engines"] % 1 != 0)
        ),
        "Number.of.Engines"
    ].value_counts()
)

Series([], Name: count, dtype: int64)

In [261]:
AviationData_Copy["Purpose.of.flight"].value_counts(dropna=False)

Purpose.of.flight
Personal                     8220
Instructional                1930
NaN                          1847
Aerial Application            585
Business                      337
Positioning                   208
Unknown                       163
Aerial Observation            133
Skydiving                     103
Other Work Use                100
Banner Tow                     73
Flight Test                    67
Ferry                          61
Executive/corporate            54
Glider Tow                     28
Public Aircraft - Federal      26
Public Aircraft - State        18
Public Aircraft                16
Air Race show                  12
Firefighting                   11
Public Aircraft - Local        11
PUBS                            3
Air Drop                        2
ASHO                            2
Name: count, dtype: int64

In [262]:
AviationData_Copy["Purpose.of.flight"] = (
    AviationData_Copy["Purpose.of.flight"]
    .str.strip()
    .str.upper()
)

In [263]:
AviationData_Copy["Broad.phase.of.flight"].value_counts(dropna=False)

Broad.phase.of.flight
NaN            13951
Cruise            15
Approach          11
Takeoff            9
Maneuvering        6
Landing            6
Descent            4
Climb              4
Unknown            3
Go-around          1
Name: count, dtype: int64

In [264]:
AviationData_Copy["Broad.phase.of.flight"] = (
    AviationData_Copy["Broad.phase.of.flight"]
    .replace(["UNKNOWN", "UNK", ""], np.nan)
)

In [265]:
for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(AviationData_Copy[col].value_counts(dropna=False))

--- Engine.Type ---
Engine.Type
RECIPROCATING      10492
NaN                 2437
TURBO PROP           739
TURBO FAN            295
TURBO JET             30
UNKNOWN               10
TURBO SHAFT            5
GEARED TURBOFAN        1
UNK                    1
Name: count, dtype: int64

--- Weather.Condition ---
Weather.Condition
VMC    11495
NaN     1793
IMC      722
Name: count, dtype: int64

--- Number.of.Engines ---
Number.of.Engines
1.0    10915
2.0     1695
NaN     1355
4.0       40
3.0        5
Name: count, dtype: int64

--- Purpose.of.flight ---
Purpose.of.flight
PERSONAL                     8220
INSTRUCTIONAL                1930
NaN                          1847
AERIAL APPLICATION            585
BUSINESS                      337
POSITIONING                   208
UNKNOWN                       163
AERIAL OBSERVATION            133
SKYDIVING                     103
OTHER WORK USE                100
BANNER TOW                     73
FLIGHT TEST                    67
FERRY                          61
EXECUTIVE/CORPORATE            54
GLIDER TOW                     28
PUBLIC AIRCRAFT - FEDERAL      26
PUBLIC AIRCRAFT - STATE        18
PUBLIC AIRCRAFT                16
AIR RACE SHOW                  12
FIREFIGHTING                   11
PUBLIC AIRCRAFT - LOCAL        11
PUBS                            3
AIR DROP                        2
ASHO                            2
Name: count, dtype: int64

--- Broad.phase.of.flight ---
Broad.phase.of.flight
NaN            13951
Cruise            15
Approach          11
Takeoff            9
Maneuvering        6
Landing            6
Descent            4
Climb              4
Unknown            3
Go-around          1
Name: count, dtype: int64

### Cleaning Tasks for Other Columns

1. **Engine.Type:** Standardized capitalization and removed leading and trailing spaces to ensure consistent engine-type categories.
2. **Weather.Condition:** Standardized category labels and treated unknown-value placeholders as missing because they do not represent a confirmed weather condition.
3. **Number.of.Engines:** Converted values to numeric format and identified zero, negative, or non-integer values for investigation.
4. **Purpose.of.flight:** Standardized capitalization and removed extra spaces to prevent duplicate categories caused by formatting inconsistencies.
5. **Broad.phase.of.flight:** Standardized category labels and treated unknown-value placeholders as missing.
6. **Missing values and rare categories:** Retained missing values and uncommon categories unless there was evidence that a value was invalid or represented a placeholder.

In [266]:
AviationData_Copy.isna().sum()

Event.Id                         0
Investigation.Type               0
Accident.Number                  0
Event.Date                       0
Location                         0
Country                          0
Latitude                       958
Longitude                      958
Airport.Code                  4499
Airport.Name                  4415
Injury.Severity                320
Aircraft.damage                  0
Aircraft.Category                0
Registration.Number              4
Make                             0
Model                            0
Amateur.Built                    0
Number.of.Engines             1355
Engine.Type                   2437
FAR.Description                188
Schedule                     12827
Purpose.of.flight             1847
Air.carrier                   6501
Total.Fatal.Injuries             0
Total.Serious.Injuries           0
Total.Minor.Injuries             0
Total.Uninjured                  0
Weather.Condition             1793
Broad.phase.of.flight        13951
Report.Status                 3056
Publication.Date               469
Total.Injuries                   0
Total.Passengers                 0
Fatal_Serious_Injury_Rate      334
Aircraft_destroyed               0
Make_Model                       0
dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [267]:
AviationData_Copy = AviationData_Copy.dropna(subset=["Latitude", "Longitude", "Schedule"])

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [268]:
AviationData_Copy.to_csv("AviationData_Cleaned.csv", index=False)